Update to latest centos 7 prereqs image (#46422)
* Update to latest centos 7 prereqs image

* Fix stringop-overflow in interop tests
Warnings were of the form:

```sh
/runtime/src/tests/Interop/BestFitMapping/BestFitMappingNative.cpp:94:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
   94 |     strncpy(pBack, pStr, len);
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~
/runtime/src/tests/Interop/BestFitMapping/BestFitMappingNative.cpp:92:24: note: length computed here
   92 |     size_t len = strlen(pStr) + 1; //+1, Include the NULL Character.
      |                  ~~~~~~^~~~~~
```